-- Seed-Erweiterung Welle 8 (Gummis/Weichgummis): EAN/PZN-Eintraege
-- mit belegter Tagesdosis. Alle verified=true (kuratiert), niemals
-- Ueberschreiben. Barcodes normalisiert wie extractProductCode
-- (fuehrende Nullen bei Codes laenger als 8 Stellen entfernt).

insert into public.product_cache (barcode, language, result, model, verified)
values
('710535656794', 'de', '{"productName": "Ah-mazing Hair* Vitamin mit Biotin", "brand": "Bears with Benefits", "confidence": 0, "ingredients": [{"name": "Biotin", "form": null, "amount": "10000", "unit": "µg"}, {"name": "Vitamin C", "form": null, "amount": "12", "unit": "mg"}, {"name": "Vitamin E", "form": null, "amount": "1.8", "unit": "mg α-TE"}, {"name": "Vitamin B6", "form": null, "amount": "1", "unit": "mg"}, {"name": "Jod", "form": null, "amount": "22.5", "unit": "µg"}, {"name": "Zink", "form": null, "amount": "1.5", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('745760685165', 'de', '{"productName": "One Bear a Day Immune* Vitamin", "brand": "Bears with Benefits", "confidence": 0, "ingredients": [{"name": "Vitamin D", "form": null, "amount": "5", "unit": "µg"}, {"name": "Vitamin E", "form": null, "amount": "6", "unit": "mg α-TE"}, {"name": "Niacin", "form": null, "amount": "8", "unit": "mg NE"}, {"name": "Vitamin B6", "form": null, "amount": "0.70", "unit": "mg"}, {"name": "Vitamin B12", "form": null, "amount": "1.3", "unit": "µg"}, {"name": "Biotin", "form": null, "amount": "25", "unit": "µg"}, {"name": "Vitamin C", "form": null, "amount": "20", "unit": "mg"}, {"name": "Propolisextrakt", "form": null, "amount": "10", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('4260717770535', 'de', '{"productName": "Queen of Iron Power* Complex", "brand": "Bears with Benefits", "confidence": 0, "ingredients": [{"name": "Vitamin D", "form": null, "amount": "10", "unit": "µg"}, {"name": "Vitamin B1", "form": null, "amount": "0.2", "unit": "mg"}, {"name": "Vitamin B12", "form": null, "amount": "17.3", "unit": "µg"}, {"name": "Jod", "form": null, "amount": "150", "unit": "µg"}, {"name": "Eisen", "form": null, "amount": "7", "unit": "mg"}, {"name": "Vitamin C", "form": null, "amount": "30", "unit": "mg"}, {"name": "Vitamin B6", "form": null, "amount": "0.7", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('4009932132571', 'de', '{"productName": "Doppelherz aktiv Haut + Haare + Nägel Gums", "brand": "Doppelherz", "confidence": 0, "ingredients": [{"name": "Vitamin A", "form": null, "amount": "200", "unit": "µg RE"}, {"name": "Vitamin E", "form": null, "amount": "6", "unit": "mg α-TE"}, {"name": "Vitamin C", "form": null, "amount": "20", "unit": "mg"}, {"name": "Niacin", "form": null, "amount": "8", "unit": "mg NE"}, {"name": "Vitamin B6", "form": null, "amount": "0.7", "unit": "mg"}, {"name": "Folsäure", "form": null, "amount": "100", "unit": "µg"}, {"name": "Vitamin B12", "form": null, "amount": "2.5", "unit": "µg"}, {"name": "Biotin", "form": null, "amount": "500", "unit": "µg"}, {"name": "Zink", "form": null, "amount": "5", "unit": "mg"}, {"name": "Selen", "form": null, "amount": "14", "unit": "µg"}, {"name": "Jod", "form": null, "amount": "75", "unit": "µg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('4009932136203', 'de', '{"productName": "Doppelherz aktiv Kollagen Gums", "brand": "Doppelherz", "confidence": 0, "ingredients": [{"name": "Kollagenhydrolysat", "form": null, "amount": "1000", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('4009932134872', 'de', '{"productName": "Doppelherz aktiv Melatonin Gums", "brand": "Doppelherz", "confidence": 0, "ingredients": [{"name": "Vitamin B6", "form": null, "amount": "1.4", "unit": "mg"}, {"name": "Melatonin", "form": null, "amount": "1", "unit": "mg"}, {"name": "Kamillenblüten-Extrakt", "form": null, "amount": "20", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('18129355', 'de', '{"productName": "Doppelherz aktiv Melatonin Gums", "brand": "Doppelherz", "confidence": 0, "ingredients": [{"name": "Vitamin B6", "form": null, "amount": "1.4", "unit": "mg"}, {"name": "Melatonin", "form": null, "amount": "1", "unit": "mg"}, {"name": "Kamillenblüten-Extrakt", "form": null, "amount": "20", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('4009932134483', 'de', '{"productName": "Doppelherz aktiv Vitamin D3 2000 I.E. Gums", "brand": "Doppelherz", "confidence": 0, "ingredients": [{"name": "Vitamin D3", "form": null, "amount": "50", "unit": "µg (2000 I.E.)"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('4066447884807', 'de', '{"productName": "Mivolis Melatonin Weichgummies", "brand": "Mivolis", "confidence": 0, "ingredients": [{"name": "Melatonin", "form": null, "amount": "1.6", "unit": "mg"}, {"name": "Vitamin B6", "form": null, "amount": "1.5", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('4066447833584', 'de', '{"productName": "Mivolis Multivitamin Gummies", "brand": "Mivolis", "confidence": 0, "ingredients": [{"name": "Folsäure", "form": null, "amount": "200", "unit": "µg"}, {"name": "Niacin", "form": null, "amount": "16", "unit": "mg"}, {"name": "Biotin", "form": null, "amount": "50", "unit": "µg"}, {"name": "Vitamin B2", "form": null, "amount": "0.35", "unit": "mg"}, {"name": "Vitamin A", "form": null, "amount": "200", "unit": "µg"}, {"name": "Vitamin B12", "form": null, "amount": "2.5", "unit": "µg"}, {"name": "Vitamin B6", "form": null, "amount": "1.4", "unit": "mg"}, {"name": "Vitamin C", "form": null, "amount": "80", "unit": "mg"}, {"name": "Vitamin D", "form": null, "amount": "10", "unit": "µg"}, {"name": "Vitamin E", "form": null, "amount": "12", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true)
on conflict (barcode, language) do nothing;
