-- Seed-Erweiterung Welle 9 (Extrasparte Homoeopathie, DHU): PZN-
-- Eintraege als reine Dokumentation, ingredients IMMER leer —
-- Potenzen enthalten keine analysierbaren Naehrstoffmengen.
-- Alle verified=true, niemals Ueberschreiben.

insert into public.product_cache (barcode, language, result, model, verified)
values
('02580415', 'de', '{"productName": "DHU Schüßler-Salz Nr. 1 Calcium fluoratum D12, 200 Tabletten", "brand": "DHU Schüßler-Salze", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Registriertes homöopathisches Arzneimittel, daher ohne Angabe einer therapeutischen Indikation. Für die Anwendung gilt die Packungsbeilage. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('02580444', 'de', '{"productName": "DHU Schüßler-Salz Nr. 2 Calcium phosphoricum D6, 200 Tabletten", "brand": "DHU Schüßler-Salze", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Registriertes homöopathisches Arzneimittel, daher ohne Angabe einer therapeutischen Indikation. Für die Anwendung gilt die Packungsbeilage. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('02580510', 'de', '{"productName": "DHU Schüßler-Salz Nr. 3 Ferrum phosphoricum D12, 200 Tabletten", "brand": "DHU Schüßler-Salze", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Registriertes homöopathisches Arzneimittel, daher ohne Angabe einer therapeutischen Indikation. Für die Anwendung gilt die Packungsbeilage. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('02580533', 'de', '{"productName": "DHU Schüßler-Salz Nr. 4 Kalium chloratum D6, 200 Tabletten", "brand": "DHU Schüßler-Salze", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Registriertes homöopathisches Arzneimittel, daher ohne Angabe einer therapeutischen Indikation. Für die Anwendung gilt die Packungsbeilage. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('02580585', 'de', '{"productName": "DHU Schüßler-Salz Nr. 5 Kalium phosphoricum D6, 200 Tabletten", "brand": "DHU Schüßler-Salze", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Registriertes homöopathisches Arzneimittel, daher ohne Angabe einer therapeutischen Indikation. Für die Anwendung gilt die Packungsbeilage. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('02580651', 'de', '{"productName": "DHU Schüßler-Salz Nr. 6 Kalium sulfuricum D6, 200 Tabletten", "brand": "DHU Schüßler-Salze", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Registriertes homöopathisches Arzneimittel, daher ohne Angabe einer therapeutischen Indikation. Für die Anwendung gilt die Packungsbeilage. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('02580697', 'de', '{"productName": "DHU Schüßler-Salz Nr. 7 Magnesium phosphoricum D6, 200 Tabletten", "brand": "DHU Schüßler-Salze", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Registriertes homöopathisches Arzneimittel, daher ohne Angabe einer therapeutischen Indikation. Für die Anwendung gilt die Packungsbeilage. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('02580786', 'de', '{"productName": "DHU Schüßler-Salz Nr. 8 Natrium chloratum D6, 200 Tabletten", "brand": "DHU Schüßler-Salze", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Registriertes homöopathisches Arzneimittel, daher ohne Angabe einer therapeutischen Indikation. Für die Anwendung gilt die Packungsbeilage. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('02580823', 'de', '{"productName": "DHU Schüßler-Salz Nr. 9 Natrium phosphoricum D6, 200 Tabletten", "brand": "DHU Schüßler-Salze", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Registriertes homöopathisches Arzneimittel, daher ohne Angabe einer therapeutischen Indikation. Für die Anwendung gilt die Packungsbeilage. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('02580881', 'de', '{"productName": "DHU Schüßler-Salz Nr. 10 Natrium sulfuricum D6, 200 Tabletten", "brand": "DHU Schüßler-Salze", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Registriertes homöopathisches Arzneimittel, daher ohne Angabe einer therapeutischen Indikation. Für die Anwendung gilt die Packungsbeilage. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('02581030', 'de', '{"productName": "DHU Schüßler-Salz Nr. 11 Silicea D12, 200 Tabletten", "brand": "DHU Schüßler-Salze", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Registriertes homöopathisches Arzneimittel, daher ohne Angabe einer therapeutischen Indikation. Für die Anwendung gilt die Packungsbeilage. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('02581053', 'de', '{"productName": "DHU Schüßler-Salz Nr. 12 Calcium sulfuricum D6, 200 Tabletten", "brand": "DHU Schüßler-Salze", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Registriertes homöopathisches Arzneimittel, daher ohne Angabe einer therapeutischen Indikation. Für die Anwendung gilt die Packungsbeilage. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('10545864', 'de', '{"productName": "DHU Schüßler-Salz Nr. 1 Calcium fluoratum D12, 10 g Globuli", "brand": "DHU Schüßler-Salze", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Registriertes homöopathisches Arzneimittel, daher ohne Angabe einer therapeutischen Indikation. Für die Anwendung gilt die Packungsbeilage. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('10545901', 'de', '{"productName": "DHU Schüßler-Salz Nr. 5 Kalium phosphoricum D6, 10 g Globuli", "brand": "DHU Schüßler-Salze", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Registriertes homöopathisches Arzneimittel, daher ohne Angabe einer therapeutischen Indikation. Für die Anwendung gilt die Packungsbeilage. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('10545924', 'de', '{"productName": "DHU Schüßler-Salz Nr. 7 Magnesium phosphoricum D6, 10 g Globuli", "brand": "DHU Schüßler-Salze", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Registriertes homöopathisches Arzneimittel, daher ohne Angabe einer therapeutischen Indikation. Für die Anwendung gilt die Packungsbeilage. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('10545976', 'de', '{"productName": "DHU Schüßler-Salz Nr. 11 Silicea D12, 10 g Globuli", "brand": "DHU Schüßler-Salze", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Registriertes homöopathisches Arzneimittel, daher ohne Angabe einer therapeutischen Indikation. Für die Anwendung gilt die Packungsbeilage. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('06584137', 'de', '{"productName": "DHU Schüßler-Salz Nr. 7 Magnesium phosphoricum D6, 420 Tabletten", "brand": "DHU Schüßler-Salze", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Registriertes homöopathisches Arzneimittel, daher ohne Angabe einer therapeutischen Indikation. Für die Anwendung gilt die Packungsbeilage. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('06584284', 'de', '{"productName": "DHU Schüßler-Salz Nr. 11 Silicea D12, 420 Tabletten", "brand": "DHU Schüßler-Salze", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Registriertes homöopathisches Arzneimittel, daher ohne Angabe einer therapeutischen Indikation. Für die Anwendung gilt die Packungsbeilage. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('12608698', 'de', '{"productName": "Rhus toxicodendron D6 DHU, 80 Tabletten", "brand": "DHU", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Registriertes homöopathisches Arzneimittel, daher ohne Angabe einer therapeutischen Indikation. Für die Anwendung gilt die Packungsbeilage. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('01758443', 'de', '{"productName": "Arnica D6 DHU, 10 g Globuli", "brand": "DHU", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Registriertes homöopathisches Arzneimittel, daher ohne Angabe einer therapeutischen Indikation. Für die Anwendung gilt die Packungsbeilage. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('15528824', 'de', '{"productName": "DHU Rhus comp. Gel, 50 g", "brand": "DHU", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Registriertes homöopathisches Arzneimittel, daher ohne Angabe einer therapeutischen Indikation. Für die Anwendung gilt die Packungsbeilage. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('13699929', 'de', '{"productName": "Nux vomica D6 DHU, 10 g Globuli", "brand": "DHU", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Registriertes homöopathisches Arzneimittel, daher ohne Angabe einer therapeutischen Indikation. Für die Anwendung gilt die Packungsbeilage. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true)
on conflict (barcode, language) do nothing;
