-- Seed-Erweiterung Welle 6 (Premium/Mikrobiom/Schwangerschaft/Import):
-- nur Eintraege mit verifiziertem Schluessel (EAN/PZN) UND belegten
-- Mengen je Tagesdosis. Vision-Eintraege gewinnen.

insert into public.product_cache (barcode, language, result, model)
values
('4260344391301', 'de', '{"productName": "Kijimea Reizdarm PRO", "brand": "Kijimea", "confidence": 0, "ingredients": [{"name": "Bifidobacterium bifidum", "form": "Bifidobacterium bifidum HI-MIMBb75 (hitzeinaktiviert)", "amount": "1x10^9", "unit": "Bakterien (Tagesdosis, 2 Kapseln)"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10'),
('4260344391400', 'de', '{"productName": "Kijimea K53 Advance", "brand": "Kijimea", "confidence": 0, "ingredients": [{"name": "Mikrokulturenstämme (53 Stämme)", "form": "u.a. B. bifidum AM96-11, P. acidilactici PA09, L. casei FB1", "amount": "20", "unit": "Mrd. KBE/Kapsel"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10'),
('5060343741614', 'de', '{"productName": "Pure Whey Protein (Nicht aromatisiert, 1kg)", "brand": "Bulk", "confidence": 0, "ingredients": [{"name": "Protein", "form": null, "amount": "23", "unit": "g"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10'),
('0748927069532', 'de', '{"productName": "Gold Standard 100% Whey", "brand": "Optimum Nutrition", "confidence": 0, "ingredients": [{"name": "Protein", "form": null, "amount": "24", "unit": "g"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10'),
('0748927069808', 'de', '{"productName": "Micronized Creatine Powder", "brand": "Optimum Nutrition", "confidence": 0, "ingredients": [{"name": "Kreatin", "form": "Monohydrat", "amount": "5", "unit": "g"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10'),
('0748927062113', 'de', '{"productName": "Essential Amino Energy", "brand": "Optimum Nutrition", "confidence": 0, "ingredients": [{"name": "Koffein", "form": null, "amount": "100", "unit": "mg"}, {"name": "Aminosaeuren", "form": null, "amount": "5", "unit": "g"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10'),
('0850013279005', 'de', '{"productName": "Collagen Peptides (Unflavored)", "brand": "Vital Proteins", "confidence": 0, "ingredients": [{"name": "Collagen Peptides", "form": "Typ I und III, aus Rinderhaut", "amount": "20", "unit": "g"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10')
on conflict (barcode, language) do nothing;
