-- Seed-Erweiterung Welle 10 (Verla, WALA): PZN-Eintraege von den
-- offiziellen Herstellerseiten. Anthroposophika als zugelassene
-- Arzneimittel gefuehrt (Stichproben-verifiziert), potenzierte
-- Zusammensetzungen ohne ingredients. verified=true, nie ueberschreiben.

insert into public.product_cache (barcode, language, result, model, verified)
values
('16917605', 'de', '{"productName": "Magnesium Verla 400 direkt Zitrone", "brand": "Verla", "confidence": 0, "ingredients": [{"name": "Magnesium (Magnesiumcitrat/Magnesiumoxid)", "form": null, "amount": "400", "unit": "mg pro Stick"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('03915467', 'de', '{"productName": "Zinkletten Verla Himbeere", "brand": "Verla", "confidence": 0, "ingredients": [{"name": "Zink (als Zinkcitrat)", "form": null, "amount": "5", "unit": "mg pro Lutschtablette"}, {"name": "Vitamin C", "form": null, "amount": "30", "unit": "mg pro Lutschtablette"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('17532161', 'de', '{"productName": "Zink Verla immun Caps", "brand": "Verla", "confidence": 0, "ingredients": [{"name": "Zink (als Zinkcitrat)", "form": null, "amount": "10", "unit": "mg pro Kapsel"}, {"name": "Vitamin C", "form": null, "amount": "80", "unit": "mg pro Kapsel"}, {"name": "Vitamin D3", "form": null, "amount": "20", "unit": "µg (800 I.E.) pro Kapsel"}, {"name": "Selen", "form": null, "amount": "55", "unit": "µg pro Kapsel"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('00828383', 'de', '{"productName": "Calcium Verla vital", "brand": "Verla", "confidence": 0, "ingredients": [{"name": "Calcium", "form": null, "amount": "600", "unit": "mg pro Tagesdosis (3 Filmtabletten)"}, {"name": "Vitamin D3", "form": null, "amount": "20", "unit": "µg (800 I.E.) pro Tagesdosis (3 Filmtabletten)"}, {"name": "Magnesium", "form": null, "amount": "100", "unit": "mg pro Tagesdosis (3 Filmtabletten)"}, {"name": "Zink", "form": null, "amount": "5", "unit": "mg pro Tagesdosis (3 Filmtabletten)"}, {"name": "Vitamin K", "form": null, "amount": "80", "unit": "µg pro Tagesdosis (3 Filmtabletten)"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('14287844', 'de', '{"productName": "Calcium Verla D direkt", "brand": "Verla", "confidence": 0, "ingredients": [{"name": "Calcium", "form": null, "amount": "400", "unit": "mg pro Stick"}, {"name": "Vitamin D3", "form": null, "amount": "10", "unit": "µg (400 I.E.) pro Stick"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('11125058', 'de', '{"productName": "Eisen Verla plus direkt", "brand": "Verla", "confidence": 0, "ingredients": [{"name": "Eisen (als Eisenfumarat)", "form": null, "amount": "10", "unit": "mg pro Stick"}, {"name": "Folsäure", "form": null, "amount": "300", "unit": "µg pro Stick"}, {"name": "Vitamin B12", "form": null, "amount": "3", "unit": "µg pro Stick"}, {"name": "Vitamin C", "form": null, "amount": "80", "unit": "mg pro Stick"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('15236257', 'de', '{"productName": "Kalium Verla purKaps", "brand": "Verla", "confidence": 0, "ingredients": [{"name": "Kalium (als Kaliumcitrat)", "form": null, "amount": "260", "unit": "mg pro Kapsel"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('01667858', 'de', '{"productName": "Magnesiocard 5 mmol", "brand": "Verla", "confidence": 0, "ingredients": [{"name": "Magnesium (als Magnesiumaspartat-hydrochlorid-Trihydrat)", "form": null, "amount": "121.5", "unit": "mg (5 mmol) pro Beutel"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Dieses Produkt ist als Arzneimittel zugelassen; für Anwendung und Dosierung gilt die Packungsbeilage."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('08912172', 'de', '{"productName": "Zink Verla 10 mg", "brand": "Verla", "confidence": 0, "ingredients": [{"name": "Zink (als Zink-D-gluconat)", "form": null, "amount": "10", "unit": "mg pro Filmtablette"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Dieses Produkt ist als Arzneimittel zugelassen; für Anwendung und Dosierung gilt die Packungsbeilage."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('01397838', 'de', '{"productName": "Calcium Verla 600 mg", "brand": "Verla", "confidence": 0, "ingredients": [{"name": "Calcium (als Calciumcarbonat)", "form": null, "amount": "600", "unit": "mg pro Filmtablette"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Dieses Produkt ist als Arzneimittel zugelassen; für Anwendung und Dosierung gilt die Packungsbeilage."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('11163863', 'de', '{"productName": "Eisen Verla 35 mg", "brand": "Verla", "confidence": 0, "ingredients": [{"name": "Eisen (Fe2+, als Eisen(II)-gluconat)", "form": null, "amount": "35", "unit": "mg pro überzogene Tablette"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Dieses Produkt ist als Arzneimittel zugelassen; für Anwendung und Dosierung gilt die Packungsbeilage."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('01032930', 'de', '{"productName": "Folverlan 0,4 mg", "brand": "Verla", "confidence": 0, "ingredients": [{"name": "Folsäure (als Folsäure-Hydrat)", "form": null, "amount": "0.4", "unit": "mg pro Tablette"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Dieses Produkt ist als Arzneimittel zugelassen; für Anwendung und Dosierung gilt die Packungsbeilage."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('00081441', 'de', '{"productName": "Gentiana Magen Globuli velati", "brand": "WALA", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Dieses Produkt ist als Arzneimittel zugelassen; für Anwendung und Dosierung gilt die Packungsbeilage."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('01448435', 'de', '{"productName": "Plantago Hustensaft", "brand": "WALA", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Dieses Produkt ist als Arzneimittel zugelassen; für Anwendung und Dosierung gilt die Packungsbeilage."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('01399961', 'de', '{"productName": "Akne-Kapseln", "brand": "WALA", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Dieses Produkt ist als Arzneimittel zugelassen; für Anwendung und Dosierung gilt die Packungsbeilage."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true)
on conflict (barcode, language) do nothing;
