-- Vollpruefung Welle 10 (Weleda/WALA): 12 WALA-PZN im Fliesstext der
-- Herstellerseiten belegt und nachgetragen. Anthroposophika bleiben
-- zugelassene Arzneimittel (bestaetigt), ingredients leer.

insert into public.product_cache (barcode, language, result, model, verified)
values
('01447861', 'de', '{"productName": "Agropyron Globuli velati", "brand": "WALA", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Dieses Produkt ist als Arzneimittel zugelassen; für Anwendung und Dosierung gilt die Packungsbeilage."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('00084882', 'de', '{"productName": "Apis Belladonna Globuli velati", "brand": "WALA", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Dieses Produkt ist als Arzneimittel zugelassen; für Anwendung und Dosierung gilt die Packungsbeilage."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('08783697', 'de', '{"productName": "Archangelica comp., Globuli velati", "brand": "WALA", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Dieses Produkt ist als Arzneimittel zugelassen; für Anwendung und Dosierung gilt die Packungsbeilage."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('08784219', 'de', '{"productName": "Aurum/Apis regina comp., Globuli velati", "brand": "WALA", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Dieses Produkt ist als Arzneimittel zugelassen; für Anwendung und Dosierung gilt die Packungsbeilage."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('00085350', 'de', '{"productName": "Bronchi Plantago Globuli velati", "brand": "WALA", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Dieses Produkt ist als Arzneimittel zugelassen; für Anwendung und Dosierung gilt die Packungsbeilage."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('00081091', 'de', '{"productName": "Calcium Quercus Globuli velati", "brand": "WALA", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Dieses Produkt ist als Arzneimittel zugelassen; für Anwendung und Dosierung gilt die Packungsbeilage."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('00081234', 'de', '{"productName": "Cantharis Blasen Globuli velati", "brand": "WALA", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Dieses Produkt ist als Arzneimittel zugelassen; für Anwendung und Dosierung gilt die Packungsbeilage."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('08785087', 'de', '{"productName": "Chamomilla e radice D6, Globuli velati", "brand": "WALA", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Dieses Produkt ist als Arzneimittel zugelassen; für Anwendung und Dosierung gilt die Packungsbeilage."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('08785928', 'de', '{"productName": "Gelsemium comp., Globuli velati", "brand": "WALA", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Dieses Produkt ist als Arzneimittel zugelassen; für Anwendung und Dosierung gilt die Packungsbeilage."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('08786419', 'de', '{"productName": "Levico comp., Globuli velati", "brand": "WALA", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Dieses Produkt ist als Arzneimittel zugelassen; für Anwendung und Dosierung gilt die Packungsbeilage."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('01448352', 'de', '{"productName": "Meteoreisen Globuli velati", "brand": "WALA", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Dieses Produkt ist als Arzneimittel zugelassen; für Anwendung und Dosierung gilt die Packungsbeilage."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('08786974', 'de', '{"productName": "Passiflora comp., Globuli velati", "brand": "WALA", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Dieses Produkt ist als Arzneimittel zugelassen; für Anwendung und Dosierung gilt die Packungsbeilage."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true)
on conflict (barcode, language) do nothing;
