-- Seed-Erweiterung Welle 9b (Extrasparte Bachblueten): PZN-Eintraege
-- als reine Dokumentation, ingredients IMMER leer (keine
-- Naehrstoff-Zuordnung). Alle verified=true, niemals Ueberschreiben.

insert into public.product_cache (barcode, language, result, model, verified)
values
('10111338', 'de', '{"productName": "Murnauers Bachblüten ORIGINAL Tropfen", "brand": "Murnauers Bachblüten", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Bachblüten-Zubereitung ohne deklarierte Nährstoffmengen. Für Anwendung und Zusammensetzung gelten die Herstellerangaben auf der Verpackung. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('10111344', 'de', '{"productName": "Murnauers Bachblüten ORIGINAL Tropfen Alkoholfrei", "brand": "Murnauers Bachblüten", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Bachblüten-Zubereitung ohne deklarierte Nährstoffmengen. Für Anwendung und Zusammensetzung gelten die Herstellerangaben auf der Verpackung. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('15583102', 'de', '{"productName": "Murnauers Bachblüten ORIGINAL Tropfen Junior", "brand": "Murnauers Bachblüten", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Bachblüten-Zubereitung ohne deklarierte Nährstoffmengen. Für Anwendung und Zusammensetzung gelten die Herstellerangaben auf der Verpackung. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('10111350', 'de', '{"productName": "Murnauers Bachblüten ORIGINAL Globulini", "brand": "Murnauers Bachblüten", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Bachblüten-Zubereitung ohne deklarierte Nährstoffmengen. Für Anwendung und Zusammensetzung gelten die Herstellerangaben auf der Verpackung. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('10111373', 'de', '{"productName": "Murnauers Bachblüten ORIGINAL Bonbons", "brand": "Murnauers Bachblüten", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Bachblüten-Zubereitung ohne deklarierte Nährstoffmengen. Für Anwendung und Zusammensetzung gelten die Herstellerangaben auf der Verpackung. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('17598964', 'de', '{"productName": "Murnauers Bachblüten ORIGINAL Bonbons Mango-Maracuja-Geschmack", "brand": "Murnauers Bachblüten", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Bachblüten-Zubereitung ohne deklarierte Nährstoffmengen. Für Anwendung und Zusammensetzung gelten die Herstellerangaben auf der Verpackung. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('10111367', 'de', '{"productName": "Murnauers Bachblüten ORIGINAL Creme", "brand": "Murnauers Bachblüten", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Bachblüten-Zubereitung ohne deklarierte Nährstoffmengen. Für Anwendung und Zusammensetzung gelten die Herstellerangaben auf der Verpackung. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('12448102', 'de', '{"productName": "Murnauers Bachblüten ORIGINAL Spray", "brand": "Murnauers Bachblüten", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Bachblüten-Zubereitung ohne deklarierte Nährstoffmengen. Für Anwendung und Zusammensetzung gelten die Herstellerangaben auf der Verpackung. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('09240220', 'de', '{"productName": "Murnauers Bachblüten BLEIB GELASSEN Kaugummis", "brand": "Murnauers Bachblüten", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Bachblüten-Zubereitung ohne deklarierte Nährstoffmengen. Für Anwendung und Zusammensetzung gelten die Herstellerangaben auf der Verpackung. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('10252725', 'de', '{"productName": "Murnauers Bachblüten KONZENTRIER DICH Globulini", "brand": "Murnauers Bachblüten", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Bachblüten-Zubereitung ohne deklarierte Nährstoffmengen. Für Anwendung und Zusammensetzung gelten die Herstellerangaben auf der Verpackung. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('09706687', 'de', '{"productName": "Murnauers Bachblüten DU SCHAFFST DAS Bonbons", "brand": "Murnauers Bachblüten", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Bachblüten-Zubereitung ohne deklarierte Nährstoffmengen. Für Anwendung und Zusammensetzung gelten die Herstellerangaben auf der Verpackung. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('01605900', 'de', '{"productName": "Murnauers Bachblüten KLEINES TRÄUMERLE Globulini Junior", "brand": "Murnauers Bachblüten", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Bachblüten-Zubereitung ohne deklarierte Nährstoffmengen. Für Anwendung und Zusammensetzung gelten die Herstellerangaben auf der Verpackung. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('09240183', 'de', '{"productName": "Murnauers Bachblüten SCHLAF GUT Tropfen", "brand": "Murnauers Bachblüten", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Bachblüten-Zubereitung ohne deklarierte Nährstoffmengen. Für Anwendung und Zusammensetzung gelten die Herstellerangaben auf der Verpackung. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('12439250', 'de', '{"productName": "Murnauers Bachblüten KOPF HOCH Globulini", "brand": "Murnauers Bachblüten", "confidence": 0, "ingredients": [], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Bachblüten-Zubereitung ohne deklarierte Nährstoffmengen. Für Anwendung und Zusammensetzung gelten die Herstellerangaben auf der Verpackung. Der Eintrag dient der Dokumentation und fließt nicht in die Nährstoff-Auswertungen ein."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true)
on conflict (barcode, language) do nothing;
