-- Seed-Erweiterung Welle 7 (Apotheken-Sortiment): PZN als
-- Primaerschluessel, Arzneimittel mit Packungsbeilagen-Hinweis.
-- Alle Eintraege verified=true (kuratiert), niemals Ueberschreiben.

insert into public.product_cache (barcode, language, result, model, verified)
values
('3884264', 'de', '{"productName": "Vitamin C Retard 500", "brand": "Cetebe", "confidence": 0, "ingredients": [{"name": "Vitamin C", "form": "Ascorbinsäure, Retard/ZEITPERLEN-Technologie", "amount": "500", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Dieses Produkt ist als Arzneimittel zugelassen; für Anwendung und Dosierung gilt die Packungsbeilage."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('173609', 'de', '{"productName": "Extra-C 600", "brand": "Cetebe", "confidence": 0, "ingredients": [{"name": "Vitamin C", "form": "Ascorbinsäure", "amount": "600", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('17513442', 'de', '{"productName": "Immun Aktiv", "brand": "Cetebe", "confidence": 0, "ingredients": [{"name": "Vitamin C", "form": null, "amount": "250", "unit": "mg"}, {"name": "Vitamin D3", "form": null, "amount": "5.0", "unit": "µg"}, {"name": "Zink", "form": null, "amount": "5.0", "unit": "mg"}, {"name": "Selen", "form": null, "amount": "28", "unit": "µg"}, {"name": "Holunderbeerenextrakt", "form": null, "amount": "100", "unit": "mg"}, {"name": "Sanddornfruchtextrakt", "form": null, "amount": "25", "unit": "mg"}, {"name": "Echinaceawurzelextrakt", "form": null, "amount": "20", "unit": "mg"}, {"name": "Curcumawurzelextrakt", "form": null, "amount": "17", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('02408188', 'de', '{"productName": "ABWEHR plus", "brand": "Cetebe", "confidence": 0, "ingredients": [{"name": "Vitamin C", "form": null, "amount": "300", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('09207553', 'de', '{"productName": "ULTRA 375 mg Kapseln", "brand": "Magnetrans", "confidence": 0, "ingredients": [{"name": "Magnesium", "form": "Magnesiumoxid", "amount": "375", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('14367589', 'de', '{"productName": "DUOAKTIV Direktgranulat-Sticks", "brand": "Magnetrans", "confidence": 0, "ingredients": [{"name": "Magnesium", "form": "Magnesiumhydrogencitrat + Magnesiumoxid", "amount": "400", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('19203734', 'de', '{"productName": "RELAXPLUS 400 mg Direktgranulat", "brand": "Magnetrans", "confidence": 0, "ingredients": [{"name": "Magnesium", "form": "Magnesiumcitrat + Magnesiumoxid", "amount": "400", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('3127830', 'de', '{"productName": "forte 150 mg Hartkapseln", "brand": "Magnetrans", "confidence": 0, "ingredients": [{"name": "Magnesium", "form": "schweres Magnesiumoxid", "amount": "150", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": ["Dieses Produkt ist als Arzneimittel zugelassen; für Anwendung und Dosierung gilt die Packungsbeilage."], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('13360622', 'de', '{"productName": "D3+K2 DuoProtect Kapseln 1.000 I.E.", "brand": "Eunova", "confidence": 0, "ingredients": [{"name": "Vitamin D3", "form": null, "amount": "25", "unit": "µg"}, {"name": "Vitamin K2", "form": null, "amount": "80", "unit": "µg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('14299942', 'de', '{"productName": "B12 Plus Ampullen", "brand": "Eunova", "confidence": 0, "ingredients": [{"name": "Vitamin B12", "form": null, "amount": "500", "unit": "µg"}, {"name": "Vitamin B1", "form": null, "amount": "1.1", "unit": "mg"}, {"name": "Vitamin B2", "form": null, "amount": "1.4", "unit": "mg"}, {"name": "Vitamin B6", "form": null, "amount": "1.4", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('10946706', 'de', '{"productName": "Magnesium 375 mg Direktgranulat Sticks", "brand": "Additiva", "confidence": 0, "ingredients": [{"name": "Magnesium", "form": null, "amount": "375", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('03045368', 'de', '{"productName": "Vitamin C + Zink Depot-Kapseln", "brand": "Additiva", "confidence": 0, "ingredients": [{"name": "Vitamin C", "form": null, "amount": "300", "unit": "mg"}, {"name": "Zink", "form": null, "amount": "5", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('10060173', 'de', '{"productName": "Multivitamin & Multimineral Orange", "brand": "Additiva", "confidence": 0, "ingredients": [{"name": "Vitamin B1", "form": null, "amount": "2.2", "unit": "mg"}, {"name": "Vitamin B2", "form": null, "amount": "2.8", "unit": "mg"}, {"name": "Niacin", "form": null, "amount": "32", "unit": "mg NE"}, {"name": "Pantothensäure", "form": null, "amount": "12", "unit": "mg"}, {"name": "Vitamin B6", "form": null, "amount": "2.8", "unit": "mg"}, {"name": "Folsäure", "form": null, "amount": "400", "unit": "µg"}, {"name": "Vitamin B12", "form": null, "amount": "5", "unit": "µg"}, {"name": "Biotin", "form": null, "amount": "100", "unit": "µg"}, {"name": "Vitamin C", "form": null, "amount": "160", "unit": "mg"}, {"name": "Vitamin E", "form": null, "amount": "24", "unit": "mg alpha-TE"}, {"name": "Calcium", "form": null, "amount": "120", "unit": "mg"}, {"name": "Phosphor", "form": null, "amount": "105", "unit": "mg"}, {"name": "Magnesium", "form": null, "amount": "56.5", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('19405774', 'de', '{"productName": "Vitamin B12 Energy Trinkampullen", "brand": "Additiva", "confidence": 0, "ingredients": [{"name": "Vitamin B12", "form": null, "amount": "500", "unit": "µg"}, {"name": "Vitamin B2", "form": null, "amount": "1.4", "unit": "mg"}, {"name": "Vitamin B6", "form": null, "amount": "1.4", "unit": "mg"}, {"name": "L-Carnitin", "form": null, "amount": "150", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true)
on conflict (barcode, language) do nothing;
