-- Seed des geteilten Produkt-Caches aus der kuratierten DACH-Recherche
-- (launch/seed-products.json, Wellen 1-3). Nur Eintraege mit verifizierter
-- EAN UND quellenbelegten Mengen. ON CONFLICT DO NOTHING: organisch
-- entstandene Vision-Eintraege werden nie ueberschrieben.

insert into public.product_cache (barcode, language, result, model)
values
('4009932004731', 'de', '{"productName": "Magnesium 400 + B1 + B6 + B12 + Folsäure", "brand": "Doppelherz", "confidence": 0, "ingredients": [{"name": "Magnesium", "form": null, "amount": "400", "unit": "mg"}, {"name": "Vitamin B1", "form": null, "amount": "4.2", "unit": "mg"}, {"name": "Vitamin B6", "form": null, "amount": "5", "unit": "mg"}, {"name": "Vitamin B12", "form": null, "amount": "5", "unit": "µg"}, {"name": "Folsäure", "form": null, "amount": "600", "unit": "µg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-09'),
('4008617008767', 'de', '{"productName": "Magnesium 400", "brand": "taxofit", "confidence": 0, "ingredients": [{"name": "Magnesium", "form": null, "amount": "400", "unit": "mg"}, {"name": "Vitamin B1", "form": null, "amount": "2.2", "unit": "mg"}, {"name": "Vitamin B6", "form": null, "amount": "6.0", "unit": "mg"}, {"name": "Vitamin B12", "form": null, "amount": "6.0", "unit": "µg"}, {"name": "Folsäure", "form": null, "amount": "800", "unit": "µg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-09'),
('4260124360237', 'de', '{"productName": "Magnesium-Diasporal 400 EXTRA direkt", "brand": "Magnesium-Diasporal", "confidence": 0, "ingredients": [{"name": "Magnesium", "form": null, "amount": "400", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-09'),
('4250382201922', 'de', '{"productName": "Magnesium-400-supra Kapseln", "brand": "Sanct Bernhard", "confidence": 0, "ingredients": [{"name": "Magnesium", "form": null, "amount": "400", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-09'),
('4260558410324', 'de', '{"productName": "Magnesium Komplex Kapseln", "brand": "Natural Elements", "confidence": 0, "ingredients": [{"name": "Magnesium (gesamt, aus 5 Verbindungen)", "form": null, "amount": "400", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-09'),
('4260085382989', 'de', '{"productName": "Magnesium Bisglycinat Kapseln 375 mg", "brand": "ZeinPharma", "confidence": 0, "ingredients": [{"name": "Magnesium", "form": null, "amount": "375", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-09'),
('8718309440503', 'de', '{"productName": "Magnesium Citrate 120 Capsules", "brand": "Fairvital", "confidence": 0, "ingredients": [{"name": "Magnesium", "form": null, "amount": "400", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-09'),
('4260435489535', 'de', '{"productName": "Vitamin D3 + K2 hochdosiert (180 Tabletten)", "brand": "Vitamaze", "confidence": 0, "ingredients": [{"name": "Vitamin D3", "form": null, "amount": "5000", "unit": "I.E."}, {"name": "Vitamin K2", "form": null, "amount": "100", "unit": "µg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-09'),
('7640152280245', 'de', '{"productName": "Vitamin D3 1000 IE", "brand": "effective nature", "confidence": 0, "ingredients": [{"name": "Vitamin D3", "form": null, "amount": "1000", "unit": "IE"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-09'),
('4250519604633', 'de', '{"productName": "Vitamin D3 + K2 (120 Kapseln)", "brand": "ESN", "confidence": 0, "ingredients": [{"name": "Vitamin D3", "form": null, "amount": "140", "unit": "µg"}, {"name": "Vitamin K2", "form": null, "amount": "200", "unit": "µg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-09'),
('4009932135565', 'de', '{"productName": "Vitamin C 1000 DEPOT", "brand": "Doppelherz", "confidence": 0, "ingredients": [{"name": "Vitamin C", "form": null, "amount": "1000", "unit": "mg"}, {"name": "Vitamin D3", "form": null, "amount": "25", "unit": "µg"}, {"name": "Zink", "form": null, "amount": "12", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-09'),
('4009932131253', 'de', '{"productName": "Jod + Folsäure + Eisen + B12", "brand": "Doppelherz", "confidence": 0, "ingredients": [{"name": "Jod", "form": null, "amount": "100", "unit": "µg"}, {"name": "Folsäure", "form": null, "amount": "600", "unit": "µg"}, {"name": "Eisen", "form": null, "amount": "10", "unit": "mg"}, {"name": "Vitamin B12", "form": null, "amount": "50", "unit": "µg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-09'),
('4260426838120', 'de', '{"productName": "Whey Zero Banana-Yoghurt", "brand": "IronMaxx", "confidence": 0, "ingredients": [{"name": "Eiweiß", "form": null, "amount": "40.5", "unit": "g pro Portion (50g)"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-09'),
('9008740004044', 'de', '{"productName": "Ester-C Gold: Vitamin C buffered 500", "brand": "BIOGENA", "confidence": 0, "ingredients": [{"name": "Vitamin C", "form": null, "amount": "500", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-09'),
('9120089616716', 'de', '{"productName": "Zinc Picolinate 15", "brand": "BIOGENA", "confidence": 0, "ingredients": [{"name": "Zink", "form": null, "amount": "15", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-09'),
('9120001437368', 'de', '{"productName": "OMNi-BiOTiC PANDA", "brand": "OMNi-BiOTiC", "confidence": 0, "ingredients": [{"name": "Bakterienkulturen (4 Stämme)", "form": null, "amount": "3", "unit": "Mrd. Bakterien pro 3g-Portion"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-09'),
('7680442590029', 'de', '{"productName": "Burgerstein Vitamin C retard", "brand": "Burgerstein", "confidence": 0, "ingredients": [{"name": "Vitamin C", "form": null, "amount": "500", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-09'),
('7611174200023', 'de', '{"productName": "Sponser Creatine Monohydrate Neutral", "brand": "SPONSER", "confidence": 0, "ingredients": [{"name": "Kreatin Monohydrat", "form": null, "amount": "3000", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-09'),
('7611174440559', 'de', '{"productName": "Sponser Creatine PyruMax Neutral", "brand": "SPONSER", "confidence": 0, "ingredients": [{"name": "Kreatin", "form": null, "amount": "3.0", "unit": "g"}, {"name": "Magnesium", "form": null, "amount": "57", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-09'),
('7611174121373', 'de', '{"productName": "Sponser Electrolytes Tabs Berry", "brand": "SPONSER", "confidence": 0, "ingredients": [{"name": "Natrium", "form": null, "amount": "400", "unit": "mg"}, {"name": "Kalium", "form": null, "amount": "100", "unit": "mg"}, {"name": "Chlorid", "form": null, "amount": "400", "unit": "mg"}, {"name": "Calcium", "form": null, "amount": "40", "unit": "mg"}, {"name": "Magnesium", "form": null, "amount": "20", "unit": "mg"}, {"name": "Zink", "form": null, "amount": "1.5", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-09'),
('7611174175178', 'de', '{"productName": "Sponser Magnesium-375 Exotic", "brand": "SPONSER", "confidence": 0, "ingredients": [{"name": "Magnesium", "form": null, "amount": "375", "unit": "mg"}, {"name": "Vitamin B6", "form": null, "amount": "0.4", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben/Open Food Facts, ODbL). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-09')
on conflict (barcode, language) do nothing;
