-- Vollpruefung Altbestand Chargen 3+5 (2026-08-10):
-- 1) Zwei Cache-Eintraege GELOESCHT: Diasporal-EAN nirgends belegbar,
--    ESN-D3K2-Mengen im OFF-Datensatz nicht belegbar.
-- 2) Vier Life-Extension-UPCs von den Herstellerseiten belegt → neue
--    Scan-Schluessel.

delete from public.product_cache
where barcode in ('4260124360237', '4250519604633')
  and language = 'de' and model like 'seed-%';

insert into public.product_cache (barcode, language, result, model, verified)
values
('737870145912', 'de', '{"productName": "Magnesium Caps", "brand": "Life Extension", "confidence": 0, "ingredients": [{"name": "Magnesium", "form": "Magnesium oxide, citrate, succinate", "amount": "500", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('737870194569', 'de', '{"productName": "BioActive Complete B-Complex", "brand": "Life Extension", "confidence": 0, "ingredients": [{"name": "Thiamine (Vitamin B1)", "form": "Thiamine HCl", "amount": "100", "unit": "mg"}, {"name": "Vitamin B6", "form": "Pyridoxine HCl, Pyridoxal 5''-Phosphat", "amount": "100", "unit": "mg"}, {"name": "Folate", "form": "L-5-Methyltetrahydrofolat, Calciumsalz", "amount": "680", "unit": "mcg"}, {"name": "Vitamin B12", "form": "Methylcobalamin", "amount": "300", "unit": "mcg"}, {"name": "Biotin", "form": null, "amount": "1000", "unit": "mcg"}, {"name": "Pantothenic acid", "form": "D-Calciumpantothenat", "amount": "500", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('737870231417', 'de', '{"productName": "Two-Per-Day Multivitamin", "brand": "Life Extension", "confidence": 0, "ingredients": [{"name": "Vitamin C", "form": "Ascorbic acid, Calcium- und Niacinamid-Ascorbate", "amount": "470", "unit": "mg"}, {"name": "Vitamin D3", "form": "Cholecalciferol", "amount": "50", "unit": "mcg"}, {"name": "Zinc", "form": "Zinc citrate, L-OptiZinc (Zinc mono-L-methionine sulfate)", "amount": "25", "unit": "mg"}, {"name": "Selenium", "form": "Sodium selenite, SelenoExcell (high selenium yeast), Se-Methyl L-Selenocystein", "amount": "200", "unit": "mcg"}, {"name": "Magnesium", "form": "Magnesium oxide", "amount": "100", "unit": "mg"}, {"name": "Vitamin B12", "form": "Methylcobalamin", "amount": "300", "unit": "mcg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true),
('737870198215', 'de', '{"productName": "Super Omega-3 EPA/DHA Fish Oil, Sesame Lignans & Olive Extract", "brand": "Life Extension", "confidence": 0, "ingredients": [{"name": "EPA (Eicosapentaensaeure)", "form": null, "amount": "700", "unit": "mg"}, {"name": "DHA (Docosahexaensaeure)", "form": null, "amount": "500", "unit": "mg"}, {"name": "Pure+ Wild Fish Oil Concentrate", "form": null, "amount": "2000", "unit": "mg"}, {"name": "Polyphen-Oil Olive extract", "form": "Fruit and leaf", "amount": "300", "unit": "mg"}], "dosage": {"amount": null, "unit": null}, "intakeInstruction": null, "warnings": [], "uncertainties": ["Aus kuratierter DACH-Produktrecherche (Herstellerangaben). Nicht vom Etikett gelesen; Angaben vor Übernahme prüfen."], "certifications": []}'::jsonb, 'seed-2026-08-10', true)
on conflict (barcode, language) do nothing;
